BackendBundle\Entity\Persona:
    type: entity
    table: personas
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        apellido:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        correo:
            type: integer
            nullable: true
            options:
                unsigned: false
    lifecycleCallbacks: {  }
